name: 'test build'
on:
  workflow_dispatch:

jobs:
   build-mysql:
    name: 'Build MySQL'
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ploosh_mysql
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install requirements
      run: | 
        docker build -t my-ploosh_mysql \
        --build-arg MYSQL_ROOT_PASSWORD=miaou \
        --build-arg MYSQL_PASSWORD=miaou \
        --build-arg MYSQL_DATABASE=ploosh \
        --build-arg MYSQL_USER=ploosh \
        .